version: "1"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=lotion
      - POSTGRES_USER=lotion
      - POSTGRES_PASSWORD=lotion
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: ./packages/web
    volumes:
      - ./packages/web:/usr/src/app
    depends_on:
      - postgres
    ports:
      - 3000:3000

volumes:
  postgres: ~
